### ISSUE TITLE
missing is-component helper

### ISSUE THREAD

**Issue by jakedetels** [cardstack/cardstack#1]
Using the demo app at https://github.com/ef4/emberconf-2017-demo and accessing the speakers/new route (http://localhost:4200/speakers/new), we get the error below.

> Error: Compile Error: is-component is not a helper
    at Helper.compile (http://localhost:4200/assets/vendor.js:69162:23)
    at http://localhost:4200/assets/vendor.js:69395:26
    at Array.map (native)
    at PositionalArgs.compile (http://localhost:4200/assets/vendor.js:69394:104)
    at Args.compile (http://localhost:4200/assets/vendor.js:69353:93)
    at OpcodeBuilder.compile (http://localhost:4200/assets/vendor.js:63332:29)
    at OpcodeBuilder.putArgs (http://localhost:4200/assets/vendor.js:63251:84)
    at IfSyntax.compile (http://localhost:4200/assets/vendor.js:67978:17)
    at InlineBlockCompiler.compileStatement (http://localhost:4200/assets/vendor.js:65928:61)
    at InlineBlockCompiler.compile (http://localhost:4200/assets/vendor.js:66006:22)

Per @ef4, this component should be available via the ember-cli-is-component addon, which is a dependency of the [tools package](https://github.com/cardstack/cardstack/blob/master/packages/tools/package.json#L23).

I'm able to eliminate this error by updating the tools' package.json:
original:
```js
"ember-cli-is-component": "https://github.com/ef4/ember-cli-is-component#544bf7a87689015c4f54c6697093d9f2b0d7b1ea",
```
updated:
```js
"ember-cli-if-component": "https://github.com/ef4/ember-cli-is-component#544bf7a87689015c4f54c6697093d9f2b0d7b1ea",
```

(Note the change from `-is-component` to `-if-component`).

This seems to be due to this addon having a different name in its [package.json file](https://github.com/ef4/ember-cli-is-component/blob/master/package.json#L2).

Please confirm that this is just a typo in the tools package.json file, vs. an issue that needs to be addressed elsewhere.

**Comment by ef4** [comment]
Thanks for debugging this @jakedetels.

I also opened an issue upstream to see if we can get the naming inconsistency fixed https://github.com/xcambar/ember-cli-is-component/issues/5
