### ISSUE TITLE
Unexpected non-failing errors and stack traces in tests

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1189]
If you look at the Ember tests CI results for a PR like [this one](https://travis-ci.com/cardstack/cardstack/builds/140810254) you can see some unusual stack traces sprinkled in between the passing tests. The issue goes as far back as 2 months ago, at least. These don't seem to affect our app's tests or deployment, but probably something is broken in terms of features.

```
Trace
    at new ContentType (/home/travis/build/cardstack/cardstack/packages/hub/schema/content-type.js:35:52)
    at findTypes (/home/travis/build/cardstack/cardstack/packages/hub/schema-loader.js:170:9)
    at SchemaLoader.loadFrom (/home/travis/build/cardstack/cardstack/packages/hub/schema-loader.js:60:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
cardstack/schema/content-type Error broken field: undefined
```

**Comment by jenweber** [comment]
I haven't noticed this in a while. Closed.
