### ISSUE TITLE
Internal server error for invalid Authorization header

### ISSUE THREAD

**Issue by courajs** [cardstack/cardstack#12]
With `@cardstack/authentication` installed and activated

```
🚀 ~$ curl -XPOST http://localhost:4200/cardstack -H "Authorization: Bearer asdf"
Internal Server Error
```
Server log:
```
  Error: Not a valid signed message
      at Encryptor.verifyAndDecrypt (/Users/aaron/dev/probably-right/node_modules/@cardstack/hub/encryptor.js:41:13)
      at Authentication._tokenToSession (/Users/aaron/dev/probably-right/node_modules/@cardstack/authentication/cardstack/middleware.js:65:57)
      at /Users/aaron/dev/probably-right/node_modules/@cardstack/authentication/cardstack/middleware.js:98:28
      at dispatch (/Users/aaron/dev/probably-right/node_modules/koa-compose/index.js:44:32)
      at /Users/aaron/dev/probably-right/node_modules/koa-compose/index.js:36:12
      at dispatch (/Users/aaron/dev/probably-right/node_modules/koa-compose/index.js:44:32)
      at /Users/aaron/dev/probably-right/node_modules/koa-compose/index.js:36:12
      at /Users/aaron/dev/probably-right/node_modules/@cardstack/hub/middleware-stack.js:20:13
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

It looks like the check [here](https://github.com/cardstack/cardstack/blob/bbc5e0d48bd19207ea511e6fced4dd2abe3a4cd6/packages/authentication/cardstack/middleware.js#L67) doesn't catch the exception thrown [here](https://github.com/cardstack/cardstack/blob/master/packages/hub/encryptor.js#L41)

**Comment by ef4** [comment]
Good catch. 

The existing pattern-based check is there because the underlying node `crypo` module throws exceptions like those. I think it would be fine to extend it to also catch this one, particularly if we add a test for this case that would break if somebody changes the exception wording in the future.
