### ISSUE TITLE
re-add featured cards to the home screen

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1347]
At some point the actual cards got lost during deployment(?), and right now we have images of the featured cards on the home screen, but the actual cards do not exist. We need to add them back.

**Comment by jenweber** [comment]
Partway through working on this, the hub reindexed and when it was done, it stopped serving requests for cards. The card I was working on is photo-card.

## Symptoms
- preflights (OPTIONS) succeed
- the front end is still up (`/cards/new` for example)
- Requests for specific cards start, and never finish
- Papertrail logs show that the last thing that happened before requests stopped working was a reindex

## Possible causes:
- The photo-card has a relationship to byline, and missing relationship card can cause these kind of symptoms. However I was making the card from scratch and didn't do anything with relationships, so I think this is irrelevant
- could be waiting for a db connection
- could be a faulty card causing an unhandled exception

Places to look
- db connections - the database is not getting hammered
- pgboss queue

**Comment by jenweber** [comment]
Resolution https://github.com/cardstack/cardstack/pull/1369

**Comment by jenweber** [comment]
After merging #1369, we saw that the changes didn't actually get deployed. Our deploy script wasn't `yarn install`ing. After fixing that, the code was still incorrect.

**Comment by jenweber** [comment]
I successfully made a new event-card, but while making the photo-card, I started getting 409 conflict. The logs show `Error: Merge conflict`:

```
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log: (node:64) UnhandledPromiseRejectionWarning: Error: Merge conflict
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log:     at withErrorHandling (/srv/hub/node_modules/@cardstack/git/writer.js:290:19)
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log: UnhandledPromiseRejectionWarning: Error: Merge conflict
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log:     at withErrorHandling (/srv/hub/node_modules/@cardstack/git/writer.js:290:19)
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log:     at emitWarning (internal/process/promises.js:97:15)
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log:     at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log:     at process._tickCallback (internal/process/next_tick.js:69:34)(node:64) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log: Error: Merge conflict
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log:     at withErrorHandling (/srv/hub/node_modules/@cardstack/git/writer.js:290:19)(node:64) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log: DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log:     at emitDeprecationWarning (internal/process/promises.js:111:13)
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log:     at emitWarning (internal/process/promises.js:104:3)
Feb 24 08:17:55 builder-demo_e112b3ab4ef6 node.log:     at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
Feb 24 08:17:59 builder-demo_466897354b15 node.log: cardstack/server start GET /api/content-types
Feb 24 08:17:59 builder-demo_466897354b15 node.log: cardstack/server finish GET /api/content-types 200
Feb 24 08:18:15 builder-demo_e112b3ab4ef6 node.log:     at process._tickCallback (internal/process/next_tick.js:69:34)cardstack/server start GET /codegen-modules
Feb 24 08:18:15 builder-demo_e112b3ab4ef6 node.log: cardstack/server finish GET /codegen-modules 200 
```

Additionally, requests for Cards now return a 409, which is odd:

```
Feb 24 12:02:06 builder-demo_e112b3ab4ef6 node.log: cardstack/server start OPTIONS /api/cards/local-hub%3A%3Aevent-card?format=isolated
Feb 24 12:02:06 builder-demo_e112b3ab4ef6 node.log: cardstack/server finish OPTIONS /api/cards/local-hub%3A%3Aevent-card?format=isolated 200
Feb 24 12:02:06 builder-demo_e112b3ab4ef6 node.log: cardstack/server start GET /api/cards/local-hub%3A%3Aevent-card?format=isolated
Feb 24 12:02:06 builder-demo_e112b3ab4ef6 node.log: cardstack/server finish GET /api/cards/local-hub%3A%3Aevent-card?format=isolated 409 
```

**Comment by ef4** [comment]
Last time we saw a 409 for card requests, it was because the hub was trying to create the base card automatically, but the base card already existed.

**Comment by jenweber** [comment]
The logs don't seem to indicate any attempts to creat4e the base card. All the 409s are for non-base-cards. It does always say that the base-card is out of date:

```

Feb 21 13:41:12 builder-demo_79d8ed0fb5ef node.log: cardstack/card-services Base card is out of date, updating @cardstack/base-card...
Feb 21 13:41:12 builder-demo_79d8ed0fb5ef node.log: cardstack/writers updating type=cards id=local-hub::@cardstack/base-card
Feb 21 13:41:12 builder-demo_79d8ed0fb5ef node.log: cardstack/server finish GET /api/content-types 200
Feb 21 13:41:12 builder-demo_79d8ed0fb5ef node.log: cardstack/performance/writers update local-hub::@cardstack/base-card/local-hub::@cardstack/base-card time to complete handleCardOperations: 28ms
Feb 21 13:41:12 builder-demo_79d8ed0fb5ef node.log: cardstack/performance/writers update local-hub::@cardstack/base-card/local-hub::@cardstack/base-card time to complete writer.prepareUpdate: 825ms
Feb 21 13:41:12 builder-demo_79d8ed0fb5ef node.log: cardstack/performance/writers update local-hub::@cardstack/base-card/local-hub::@cardstack/base-card time to complete beforeFinalize work (create/update card schema resources): 0ms 
```

**Comment by ef4** [comment]
Right, but the base card gets created as a side effect of other requests here:

https://github.com/cardstack/cardstack/blob/988239caa023ce77189871a83275304a782c5a4d/packages/hub/card-services.ts#L67

**Comment by jenweber** [comment]
We enabled debug level logging by changing the env vars for a deploy:

```
demo_LOG_LEVELS = '*=info,cardstack/performance/writers=debug,cardstack/card-services=debug'
```

This error popped up as well:

```
Feb 25 07:50:03 builder-demo_48ff2d46c17e node.log: cardstack/git cloning git@github.com:cardstack/builder-data.git into /tmp/cardstack-git-local-cache/git@github.com!cardstack!builder-data.git
Feb 25 07:50:03 builder-demo_48ff2d46c17e node.log:   UnknownTransportError: Git remote "git@github.com:cardstack/builder-data.git" uses an unrecognized transport protocol: "ssh"
Feb 25 07:50:03 builder-demo_48ff2d46c17e node.log:       at Function.getRemoteHelperFor (/srv/hub/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:7332:11)
Feb 25 07:50:03 builder-demo_48ff2d46c17e node.log:       at fetchPackfile (/srv/hub/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:8016:42)
Feb 25 07:50:10 builder-demo_b553adbaccce node.log: cardstack/server start GET /api/content-types
Feb 25 07:50:10 builder-demo_b553adbaccce node.log: cardstack/server finish GET /api/content-types 200
Feb 25 07:50:33 builder-demo_48ff2d46c17e node.log: cardstack/server start GET /api/content-types
Feb 25 07:50:33 builder-demo_48ff2d46c17e node.log:   UnknownTransportError: Git remote "git@github.com:cardstack/builder-data.git" uses an unrecognized transport protocol: "ssh"
Feb 25 07:50:33 builder-demo_48ff2d46c17e node.log:       at Function.getRemoteHelperFor (/srv/hub/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:7332:11)
Feb 25 07:50:33 builder-demo_48ff2d46c17e node.log:       at fetchPackfile (/srv/hub/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:8016:42)
Feb 25 07:50:40 builder-demo_b553adbaccce node.log: cardstack/server start GET /api/content-types
Feb 25 07:50:40 builder-demo_b553adbaccce node.log: cardstack/server finish GET /api/content-types 200
Feb 25 07:51:03 builder-demo_48ff2d46c17e node.log: cardstack/server start GET /api/content-types
Feb 25 07:51:03 builder-demo_48ff2d46c17e node.log:   UnknownTransportError: Git remote "git@github.com:cardstack/builder-data.git" uses an unrecognized transport protocol: "ssh"
Feb 25 07:51:03 builder-demo_48ff2d46c17e node.log:       at Function.getRemoteHelperFor (/srv/hub/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:7332:11)
Feb 25 07:51:03 builder-demo_48ff2d46c17e node.log:       at fetchPackfile (/srv/hub/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:8016:42) 
```

**Comment by jenweber** [comment]
Relevant logs after increasing log levels:

```
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: cardstack/card-utils generating on-disk card artifacts for cards/local-hub::@cardstack/base-card in /tmp/card_modules/local-hub/@cardstack/base-card
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: cardstack/card-services the current base card: {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:   "data": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     "id": "local-hub::@cardstack/base-card",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     "type": "cards",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     "attributes": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "field-order": [],
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "isolated-css": ".cardstack_base-card-isolated {\n\n}\n",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "embedded-css": ".cardstack_base-card-embedded {\n\n}\n",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "adoption-chain": []
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     },
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     "relationships": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "fields": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:         "data": []
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       },
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "model": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:         "data": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:           "type": "local-hub::@cardstack/base-card",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:           "id": "local-hub::@cardstack/base-card"
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:         }
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       }
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     }
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:   },
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:   "included": [
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "id": "local-hub::@cardstack/base-card",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "type": "local-hub::@cardstack/base-card"
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     }
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:   ]
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: }
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: cardstack/card-services new base card: {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:   "data": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     "id": "local-hub::@cardstack/base-card",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     "type": "cards",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     "attributes": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "isolated-css": ".cardstack_base-card-isolated {\n\n}\n",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "embedded-css": ".cardstack_base-card-embedded {\n\n}\n"
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     },
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     "relationships": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "adopted-from": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:         "data": null
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       },
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "fields": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:         "data": []
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       },
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "model": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:         "data": {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:           "type": "local-hub::@cardstack/base-card",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:           "id": "local-hub::@cardstack/base-card"
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:         }
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       }
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     }
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:   },
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:   "included": [
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     {
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "id": "local-hub::@cardstack/base-card",
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:       "type": "local-hub::@cardstack/base-card"
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     }
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:   ]
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: }
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: cardstack/card-services Base card is out of date, updating @cardstack/base-card...
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: cardstack/writers updating type=cards id=local-hub::@cardstack/base-card
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: cardstack/performance/writers update local-hub::@cardstack/base-card/local-hub::@cardstack/base-card time to complete handleCardOperations: 14ms
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: cardstack/performance/writers update local-hub::@cardstack/base-card/local-hub::@cardstack/base-card time to complete writer.prepareUpdate: 828ms
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: cardstack/performance/writers update local-hub::@cardstack/base-card/local-hub::@cardstack/base-card time to complete beforeFinalize work (create/update card schema resources): 1ms
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: (node:62) UnhandledPromiseRejectionWarning: Error: Merge conflict
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log:     at withErrorHandling (/srv/hub/node_modules/@cardstack/git/writer.js:290:19)
Feb 25 11:15:03 builder-demo_29d0b20ebeef node.log: UnhandledPromiseRejectionWarning: Error: Merge conflict 
```

**Comment by jenweber** [comment]
It looks like we never invalidate the base card. In `data.js`:

```
async function invalidate(cardId, latestVersion) {
  if (cardId === baseCard) {
    return;
  } // don't invalidate the base card--it never changes, and everything descends from it
```

**Comment by jenweber** [comment]
I think there's a fatal loop where the indexer asks for a card, asks to make sure the base card exists, the base card tries to update, and a merge conflict occurs, so none of the indexers ever finish.

**Comment by jenweber** [comment]
The card is determined by hard-coded info in `cards/base-card/index.ts`. Hassan says the base-card should never be pulled from the git data source, so that would possibly explain why the card in github doesn't match anything else.

So where does the "old" card come from?

**Comment by jenweber** [comment]
## Notes from further debugging

Base card is getting written to non-emphemeral storage
To fix this - in the schema, you have to tell it what the data source per type
Set the data source to ephemeral for the base card if we needed to fix this long term

To work around this, need to remove the card from git:

First, turn off builder so it doesn’t go out of control
https://github.com/cardstack/cardstack/wiki/Core-developer-cheat-sheet#manually-reindex-the-hub up until step 4

(sc.builder.stack.cards)

Deleted the card from git

Clear out the index

When we kick off indexing, we add a job to the job queue. When the job queue gets to that item, it executes it. But for a failed job, the queue timeout is 2 hours. You can bring things to a halt. Before issuing a reindex, clear the queue.

Have to use zerotier for this step. Don’t forget about etc/hosts.

Start up postico, connect, pgboss_production, under pgboss schema, there is a job table.

Update state failed means a blocking job. Cleared it.

In pgsearch, meta, delete the “default” row. This holds the last commit sha that keeps track of where you left off. When you delete this row, you are telling the indexer to run on everything again.

Reindex command - look up the url for our API and get ready to run it

Bring the Hub back up:
Run the scale command: `docker -H $remote service scale hub_hub=1`
Look at the logs to see if it’s working

Debugging… 

(saw a “can’t find docker container” error)
`docker -H $remote service rm hub_hub`
Force a redeploy via GH actions.
Deploy will appear to fail. This is expected/ok.

`docker -h $remote ps --all` to see the docker containers
(remote was set by socat command earlier)

(saw the same error about merge conflicts)

Resuming….

`curl -x post https://builder-hub.stack.cards/reindex` forces reindex
(watch papertrail logs)
(didn’t help)

Tried to remove the git card from the index itself. Scaled the sc to zero again, removed the pgboss entry again.

Not seeing anymore merge conflicts

Realized it was still hanging around as a content type.

Did another reindex.

Squashed all the commits and force pushed to the data repo.

## Current status:
Still down.
Somehow, the seed data cards aren't getting indexed even though they are in git...

## For the future:
If this happens again - for the content type base card, specify that the data source should be ephemeral, not git.

**Comment by jenweber** [comment]
Hotfixes:
https://github.com/cardstack/cardstack/commit/a4631aaa3b804e7c5cc7d1100912323e4a6bf412

https://github.com/cardstack/cardstack/commit/738ba0ff2fd340b435edf406b3f4e646f394c198

Theses seemed to temporarily restore functionality, but after making the photo-card, I am not able to save edits.

**Comment by jenweber** [comment]
We also had to skip running seeds in production or we would get conflicts there too. #1413

**Comment by jenweber** [comment]
I found that I had to squash the commit history in order for the deployed stack to allow me to make changes to cards that were seeds in the past. Steps for manually reindexing after making changes to the git data source are here: https://github.com/cardstack/cardstack/wiki/Core-developer-cheat-sheet#manually-reindex-the-hub-in-deployment

Closed with successful editing of featured cards in deployment.
