### ISSUE TITLE
Make `ethereum-indexer` tests work on Node 10

### ISSUE THREAD

**Issue by Turbo87** [cardstack/cardstack#485]
https://github.com/cardstack/cardstack/pull/430 tested out running CI on Node 10, but for some unknown reason the tests about the `ethereum-indexer` seem to fail in the `beforeEach()` hook:
```
  1) Contract: SampleToken ethereum-indexer "before each" hook: setup for "can generate schema from ERC-20 contract`s ABI":
     RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -1410909097
      at checkInt (internal/buffer.js:35:11)
      at writeU_Int32BE (internal/buffer.js:623:3)
      at Buffer.writeUInt32BE (internal/buffer.js:636:10)
      at WebSocketFrame.toBuffer (/home/travis/build/cardstack/cardstack/node_modules/websocket/lib/WebSocketFrame.js:257:24)
      at WebSocketConnection.sendFrame (/home/travis/build/cardstack/cardstack/node_modules/websocket/lib/WebSocketConnection.js:852:43)
      at WebSocketConnection.fragmentAndSend (/home/travis/build/cardstack/cardstack/node_modules/websocket/lib/WebSocketConnection.js:788:14)
      at WebSocketConnection.sendUTF (/home/travis/build/cardstack/cardstack/node_modules/websocket/lib/WebSocketConnection.js:728:10)
      at W3CWebSocket.send (/home/travis/build/cardstack/cardstack/node_modules/websocket/lib/W3CWebSocket.js:116:26)
      at WebsocketProvider.send (/home/travis/build/cardstack/cardstack/node_modules/web3-providers-ws/src/index.js:223:21)
      at RequestManager.send (/home/travis/build/cardstack/cardstack/node_modules/web3-core-requestmanager/src/index.js:129:66)
      at RequestManager.removeSubscription (/home/travis/build/cardstack/cardstack/node_modules/web3-core-requestmanager/src/index.js:209:14)
      at Subscription.unsubscribe (/home/travis/build/cardstack/cardstack/node_modules/web3-core-subscriptions/src/subscription.js:175:33)
      at EthereumClient.stop (cardstack/client.js:92:42)
      at EthereumClient.stopAll (cardstack/client.js:83:18)
      at EthereumClient._reconnect (cardstack/client.js:58:16)
      at EthereumClient.getBlockHeight (cardstack/client.js:107:18)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by habdelra** [comment]
I'm working inside the etheruem plugin right now, so I'll take a stab at fixing this.

**Comment by habdelra** [comment]
This was fixed here: https://github.com/ethereum/web3.js/issues/1613
