### ISSUE TITLE
Cleanup deprecation ember-data:method-calls-on-destroyed-store

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#741]
When running the tools ember test I noticed the following deprecation. Let's clean this up.

```
ok 15 Chrome 73.0 - [1798 ms] - Acceptance | tools: track field dirtiness in owned, related records
    ---
        Log: |
            { type: 'warn',
              text:
               '\'DEPRECATION: Attempted to call store.serializerFor(), but the store instance has already been destroyed. [deprecation id: ember-data:method-calls-on-destroyed-store]\\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:17252:29)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:17354:17)\\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:17276:17)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:17354:17)\\n        at invoke (http://localhost:7357/assets/vendor.js:17363:17)\\n        at Object.deprecate (http://localhost:7357/assets/vendor.js:17335:34)\\n        at assertDestroyedStore (http://localhost:7357/assets/vendor.js:98574:73)\\n        at Class.serializerFor (http://localhost:7357/assets/vendor.js:98269:9)\\n        at Snapshot.serialize (http://localhost:7357/assets/vendor.js:89744:32)\'\n' }
            { type: 'warn',
              text:
               '\'DEPRECATION: Attempted to call store.serializerFor(), but the store instance has already been destroyed. [deprecation id: ember-data:method-calls-on-destroyed-store]\\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:17252:29)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:17354:17)\\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:17276:17)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:17354:17)\\n        at invoke (http://localhost:7357/assets/vendor.js:17363:17)\\n        at Object.deprecate (http://localhost:7357/assets/vendor.js:17335:34)\\n        at assertDestroyedStore (http://localhost:7357/assets/vendor.js:98574:73)\\n        at Class.serializerFor (http://localhost:7357/assets/vendor.js:98269:9)\\n        at Snapshot.serialize (http://localhost:7357/assets/vendor.js:89744:32)\'\n' }
            { type: 'warn',
              text:
               '\'DEPRECATION: Attempted to call store.serializerFor(), but the store instance has already been destroyed. [deprecation id: ember-data:method-calls-on-destroyed-store]\\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:17252:29)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:17354:17)\\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:17276:17)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:17354:17)\\n        at invoke (http://localhost:7357/assets/vendor.js:17363:17)\\n        at Object.deprecate (http://localhost:7357/assets/vendor.js:17335:34)\\n        at assertDestroyedStore (http://localhost:7357/assets/vendor.js:98574:73)\\n        at Class.serializerFor (http://localhost:7357/assets/vendor.js:98269:9)\\n        at Snapshot.serialize (http://localhost:7357/assets/vendor.js:89744:32)\'\n' }
            { type: 'warn',
              text:
               '\'DEPRECATION: Attempted to call store.serializerFor(), but the store instance has already been destroyed. [deprecation id: ember-data:method-calls-on-destroyed-store]\\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:17252:29)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:17354:17)\\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:17276:17)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:17354:17)\\n        at invoke (http://localhost:7357/assets/vendor.js:17363:17)\\n        at Object.deprecate (http://localhost:7357/assets/vendor.js:17335:34)\\n        at assertDestroyedStore (http://localhost:7357/assets/vendor.js:98574:73)\\n        at Class.serializerFor (http://localhost:7357/assets/vendor.js:98269:9)\\n        at Snapshot.serialize (http://localhost:7357/assets/vendor.js:89744:32)\'\n' }
    ...
```

**Comment by ef4** [comment]
While we're at it, anybody should feel free to run ember-cli-update on all the packages and get us onto latest deps.

**Comment by jenweber** [comment]
The deprecation seems to come from some part of `validate` happening after the test teardown, which destroys the store:

```js
// cs-active-composition-panel
let errors = yield this.get('data').validate(this.model);`
```
