### ISSUE TITLE
Debug embroider build failure for ember-lodash

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#797]
Something changed in the last couple weeks in our dependencies. This package.json and yarn lock works:

[package.txt](https://github.com/cardstack/cardstack/files/3282993/package.txt)
[yarn.txt](https://github.com/cardstack/cardstack/files/3282994/yarn.txt)

This does not:

[package.txt](https://github.com/cardstack/cardstack/files/3283005/package.txt)
[yarn.txt](https://github.com/cardstack/cardstack/files/3283006/yarn.txt)

The failure is:

```
[BroccoliMergeTrees] error while merging the following:
  1.  [BroccoliMergeTrees]
  2.  [RewritePackageJSON: embroider:core:rewrite-package-json]
Merge error: file package.json exists in /var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-76230waOIF5hVf644/out-12-broccoli_merge_trees and /var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-76230waOIF5hVf644/out-14-rewrite_package_json_embroider_core_rewrite_package_json
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
        at BroccoliMergeTrees
-~- created here: -~-
    at BroccoliMergeTrees.Plugin (/Users/jenweber/projects/embroider/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/jenweber/projects/embroider/node_modules/broccoli-merge-trees/index.js:16:10)
    at Object.BroccoliMergeTrees [as default] (/Users/jenweber/projects/embroider/node_modules/broccoli-merge-trees/index.js:10:53)
    at V1Addon.get v2Tree [as v2Tree] (/Users/jenweber/projects/embroider/packages/compat/src/v1-addon.js:304:46)
    at oldPackages.map.pkg (/Users/jenweber/projects/embroider/packages/compat/src/build-compat-addon.js:42:48)
    at Array.map (<anonymous>)
    at buildCompatAddon (/Users/jenweber/projects/embroider/packages/compat/src/build-compat-addon.js:42:33)
    at Object.cachedBuildCompatAddon [as default] (/Users/jenweber/projects/embroider/packages/compat/src/build-compat-addon.js:13:16)
    at CompatAddons.movedAddons.map.oldPkg (/Users/jenweber/projects/embroider/packages/compat/src/compat-addons.js:39:105)
    at Array.map (<anonymous>)
-~- (end) -~-
```

**Comment by jenweber** [comment]
We discovered a breaking change in canary Ember CLI. Ed will chase it down so that we can keep running on the latest Ember, and I'll do #799 so that we only battle dependency changes when we choose to, and our users get a consistent app generated while they run on a particular version of the CLI.
