### ISSUE TITLE
Bug - Node 8 tests often fail on the first try in CI

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#833]
I have to rerun these in CI about 50% of the time.

```
 1) Contract: ethereum-addresses indexing @cardstack/ethereum - ethereum-addresses using tracked address model as an id field can search for transactions for a tracked address only in blocks that have not yet been processed (e.g. hub stops and restarts during which transactions have occurred):

      AssertionError: expected 1 to equal 0
      + expected - actual
      -1
      +0

      at Context.<anonymous> (truffle-tests/addresses-test.js:479:41)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by jenweber** [comment]
I think this is better after we moved to Node 10, and we're now on 12. Closed.
