### ISSUE TITLE
Bug: Failed to execute 'pushState' on 'History'

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#866]
This seems to appear when saving a has-many relationship. To reproduce, see the project-template's movielist branch. Click edit content, click on watched movies, try removing a watched movie in the right edge, and hit save. It isn't actually that bad but _looks_ bad because it is logged as a security error.

This bug seems to go back to the original version of Cardstack used in the movielist tutorial, `0.13.67`.

It does not seem to be fatal to the application flow. Here's the [source code where it happens](https://github.com/emberjs/ember.js/blob/e8a6420f39d0a6a6f67a85f62f30fbb5c4339507/packages/%40ember/-internals/routing/lib/location/history_location.ts) (in Ember)

```
rsvp.js:23 Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost:4200' and URL 'http://localhost:4200/'.
    at HistoryLocation.pushState (http://localhost:4200/assets/vendor.js:32809:40)
    at HistoryLocation.setURL (http://localhost:4200/assets/vendor.js:32755:14)
    at Class.afterModelSaved (http://localhost:4200/assets/vendor.js:101871:16)
    at Backburner._join (http://localhost:4200/assets/vendor.js:65933:23)
    at Backburner.join (http://localhost:4200/assets/vendor.js:65700:19)
    at join (http://localhost:4200/assets/vendor.js:53275:23)
    at http://localhost:4200/assets/vendor.js:23430:34
    at flaggedInstrument (http://localhost:4200/assets/vendor.js:50966:85)
    at http://localhost:4200/assets/vendor.js:23429:53
    at http://localhost:4200/assets/vendor.js:23395:101'
```

**Comment by jenweber** [comment]
obsolete with new-hub
